---
- hosts: all
  remote_user: azure
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:

     - name: disable swap
       shell: |
               sudo swapoff -a
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

     - name: modprobe
       shell: |
               sudo modprobe overlay
               sudo modprobe br_netfilter

     - name: Create containerd config file
       file:
         path: "/etc/modules-load.d/k8s.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/modules-load.d/k8s.conf"
         block: |
               overlay
               br_netfilter

     - name: Set system configurations for Kubernetes networking
       file:
         path: "/etc/ufw/sysctl.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/ufw/sysctl.conf"
         block: |
                net/bridge/bridge-nf-call-iptables = 1
                net/bridge/bridge-nf-call-ip6tables = 1
                net/bridge/bridge-nf-call-arptables = 1

     - name: install ebtables and ethtool
       shell: |
               sudo apt-get update
               sudo apt-get install -y ethtool ebtables

     - name: Apply new settings
       command: sudo sysctl --system

     - name: Ansible apt to install curl and other packages
       apt:
         update_cache: yes
         name:
           - curl
           - gnupg2
           - software-properties-common
           - apt-transport-https
           - ca-certificates 
         state: present

     - name: configure dependencies
       shell: |
               curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
               curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
               sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

     - name: install containerd
       shell: |
               sudo apt-get update && sudo apt-get install -y containerd.io
               sudo mkdir -p /etc/containerd
               sudo containerd config default | sudo tee /etc/containerd/config.toml
               sudo systemctl restart containerd
               sudo systemctl enable containerd

     - name: Create kubernetes repo file
       file:
         path: "/etc/apt/sources.list.d/kubernetes.list"
         state: "touch"

     - name: Add K8s Source
       blockinfile:
         path: "/etc/apt/sources.list.d/kubernetes.list"
         block: |
                 deb http://apt.kubernetes.io/ kubernetes-xenial main

     - name: hold kubernetes 
       shell: |
               sudo apt-mark hold kubelet kubeadm kubectl