d---
- hosts: masters
  remote_user: azure
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: initialize the cluster
      shell: sudo kubeadm init

    - name: create .kube directory
      shell: |
        export KUBECONFIG=$HOME/.kube/config
        mkdir -p /home/azure/.kube
        sudo rm -f $HOME/.kube/config
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) /home/azure/.kube/config

    - name: install network for pods
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml

    - name: Get the token for joining the worker nodes
      become: yes
      shell: sudo kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: no
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777